// This file is a placeholder that would normally be replaced by API calls
// In a real application, you would call an actual API endpoint

export const philippineProvinces = [
  "Abra",
  "Agusan del Norte",
  "Agusan del Sur",
  "Aklan",
  "Albay",
  "Antique",
  "Apayao",
  "Aurora",
  "Basilan",
  "Bataan",
  "Batanes",
  "Batangas",
  "Benguet",
  "Biliran",
  "Bohol",
  "Bukidnon",
  "Bulacan",
  "Cagayan",
  "Camarines Norte",
  "Camarines Sur",
  "Camiguin",
  "Capiz",
  "Catanduanes",
  "Cavite",
  "Cebu",
  "Cotabato",
  "Davao de Oro",
  "Davao del Norte",
  "Davao del Sur",
  "Davao Occidental",
  "Davao Oriental",
  "Dinagat Islands",
  "Eastern Samar",
  "Guimaras",
  "Ifugao",
  "Ilocos Norte",
  "Ilocos Sur",
  "Iloilo",
  "Isabela",
  "Kalinga",
  "La Union",
  "Laguna",
  "Lanao del Norte",
  "Lanao del Sur",
  "Leyte",
  "Maguindanao",
  "Marinduque",
  "Masbate",
  "Metro Manila",
  "Misamis Occidental",
  "Misamis Oriental",
  "Mountain Province",
  "Negros Occidental",
  "Negros Oriental",
  "Northern Samar",
  "Nueva Ecija",
  "Nueva Vizcaya",
  "Occidental Mindoro",
  "Oriental Mindoro",
  "Palawan",
  "Pampanga",
  "Pangasinan",
  "Quezon",
  "Quirino",
  "Rizal",
  "Romblon",
  "Samar",
  "Sarangani",
  "Siquijor",
  "Sorsogon",
  "South Cotabato",
  "Southern Leyte",
  "Sultan Kudarat",
  "Sulu",
  "Surigao del Norte",
  "Surigao del Sur",
  "Tarlac",
  "Tawi-Tawi",
  "Zambales",
  "Zamboanga del Norte",
  "Zamboanga del Sur",
  "Zamboanga Sibugay",
]

// This function would be replaced by a real API call in a production app
export function getCitiesByProvince(province: string): string[] {
  // This should be replaced by an actual API call
  // For example: return fetch(`https://psgc.gitlab.io/api/provinces/${provinceCode}/cities-municipalities/`).then(res => res.json())

  // Sample cities for common provinces - in real world this would come from API
  const provinceCities: Record<string, string[]> = {
    "Metro Manila": [
      "Caloocan",
      "Las Piñas",
      "Makati",
      "Malabon",
      "Mandaluyong",
      "Manila",
      "Marikina",
      "Muntinlupa",
      "Navotas",
      "Parañaque",
      "Pasay",
      "Pasig",
      "Pateros",
      "Quezon City",
      "San Juan",
      "Taguig",
      "Valenzuela",
    ],
    Cebu: [
      "Cebu City",
      "Mandaue",
      "Lapu-Lapu",
      "Talisay",
      "Danao",
      "Toledo",
      "Carcar",
      "Naga",
      "Bogo",
      "Balamban",
      "Dalaguete",
      "Minglanilla",
    ],
    Batangas: [
      "Batangas City",
      "Lipa",
      "Tanauan",
      "Santo Tomas",
      "Bauan",
      "San Pascual",
      "Nasugbu",
      "Calatagan",
      "Balayan",
      "Lemery",
      "Taal",
      "San Juan",
    ],
    Cavite: [
      "Cavite City",
      "Tagaytay",
      "Trece Martires",
      "Dasmariñas",
      "Bacoor",
      "Imus",
      "General Trias",
      "Tanza",
      "Silang",
      "Carmona",
      "Maragondon",
    ],
    Laguna: [
      "Santa Rosa",
      "Biñan",
      "San Pedro",
      "Calamba",
      "Los Baños",
      "San Pablo",
      "Cabuyao",
      "Pagsanjan",
      "Luisiana",
      "Majayjay",
      "Nagcarlan",
      "Pila",
    ],
    Rizal: [
      "Antipolo",
      "Cainta",
      "Taytay",
      "Angono",
      "Binangonan",
      "Rodriguez",
      "San Mateo",
      "Tanay",
      "Teresa",
      "Morong",
      "Baras",
      "Jala-Jala",
    ],
  }

  // Return cities for the province or a default set
  return (
    provinceCities[province] || [
      "City/Municipality 1",
      "City/Municipality 2",
      "City/Municipality 3",
      "City/Municipality 4",
      "City/Municipality 5",
    ]
  )
}
